name: "Tests"

"on":
  push:
    branches: ["main"]
  pull_request: null

jobs:
  run-suite:
    name: "Run suite"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        suite:
        - "lint"
        - "specs"
        - "features"
    steps:
    - uses: "actions/checkout@v4"
    - if: matrix.suite == 'lint'
      run: "docker compose run tests standardrb"
    - if: matrix.suite == 'lint'
      run: "docker compose run yaml-lint"
    - if: matrix.suite == 'specs'
      run: "docker compose run tests rspec"
    - if: matrix.suite == 'features'
      run: "docker compose run features"
